name: clean_gen_tool
description:  A CLI tool for generating clean architecture code structure in Dart/Flutter projects by Mohammad AD
version: 1.0.2
repository: https://github.com/Mohammad-AD/clean_gen_tool

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  yaml: ^3.1.3
  io: ^1.0.5

dev_dependencies:
  lints:
  test:

executables:
  clean_arch: clean_gen_tool